export const STRIPE_PIBLISHABLE_KEY = "pk_test_51RaycaHIxmqjxScp3TuKvH3IMICWJU8L3UT00zzAmOkVMm2ze1OPckcgqRcN4ydM93Degks5ZMbiLSmR4v2CDSr200WNWQDsi5"

export const COUNTRIES = [
  { code: "af", name: "Afganistán" },
  { code: "al", name: "Albania" },
  { code: "de", name: "Alemania" },
  { code: "ad", name: "Andorra" },
  { code: "ao", name: "Angola" },
  { code: "ag", name: "Antigua y Barbuda" },
  { code: "sa", name: "Arabia Saudita" },
  { code: "dz", name: "Argelia" },
  { code: "ar", name: "Argentina" },
  { code: "am", name: "Armenia" },
  { code: "au", name: "Australia" },
  { code: "at", name: "Austria" },
  { code: "az", name: "Azerbaiyán" },
  { code: "bs", name: "Bahamas" },
  { code: "bd", name: "Bangladés" },
  { code: "bb", name: "Barbados" },
  { code: "bh", name: "Baréin" },
  { code: "be", name: "Bélgica" },
  { code: "bz", name: "Belice" },
  { code: "bj", name: "Benín" },
  { code: "by", name: "Bielorrusia" },
  { code: "mm", name: "Birmania" },
  { code: "bo", name: "Bolivia" },
  { code: "ba", name: "Bosnia y Herzegovina" },
  { code: "bw", name: "Botsuana" },
  { code: "br", name: "Brasil" },
  { code: "bn", name: "Brunéi" },
  { code: "bg", name: "Bulgaria" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bi", name: "Burundi" },
  { code: "bt", name: "Bután" },
  { code: "cv", name: "Cabo Verde" },
  { code: "kh", name: "Camboya" },
  { code: "cm", name: "Camerún" },
  { code: "ca", name: "Canadá" },
  { code: "qa", name: "Catar" },
  { code: "td", name: "Chad" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  { code: "cy", name: "Chipre" },
  { code: "va", name: "Ciudad del Vaticano" },
  { code: "co", name: "Colombia" },
  { code: "km", name: "Comoras" },
  { code: "kp", name: "Corea del Norte" },
  { code: "kr", name: "Corea del Sur" },
  { code: "ci", name: "Costa de Marfil" },
  { code: "cr", name: "Costa Rica" },
  { code: "hr", name: "Croacia" },
  { code: "cu", name: "Cuba" },
  { code: "dk", name: "Dinamarca" },
  { code: "dm", name: "Dominica" },
  { code: "ec", name: "Ecuador" },
  { code: "eg", name: "Egipto" },
  { code: "sv", name: "El Salvador" },
  { code: "ae", name: "Emiratos Árabes Unidos" },
  { code: "er", name: "Eritrea" },
  { code: "sk", name: "Eslovaquia" },
  { code: "si", name: "Eslovenia" },
  { code: "es", name: "España" },
  { code: "us", name: "Estados Unidos" },
  { code: "ee", name: "Estonia" },
  { code: "sz", name: "Esuatini" },
  { code: "et", name: "Etiopía" },
  { code: "ph", name: "Filipinas" },
  { code: "fi", name: "Finlandia" },
  { code: "fj", name: "Fiyi" },
  { code: "fr", name: "Francia" },
  { code: "ga", name: "Gabón" },
  { code: "gm", name: "Gambia" },
  { code: "ge", name: "Georgia" },
  { code: "gh", name: "Ghana" },
  { code: "gd", name: "Granada" },
  { code: "gr", name: "Grecia" },
  { code: "gt", name: "Guatemala" },
  { code: "gy", name: "Guyana" },
  { code: "gn", name: "Guinea" },
  { code: "gw", name: "Guinea-Bisáu" },
  { code: "gq", name: "Guinea Ecuatorial" },
  { code: "ht", name: "Haití" },
  { code: "hn", name: "Honduras" },
  { code: "hu", name: "Hungría" },
  { code: "in", name: "India" },
  { code: "id", name: "Indonesia" },
  { code: "iq", name: "Irak" },
  { code: "ir", name: "Irán" },
  { code: "ie", name: "Irlanda" },
  { code: "is", name: "Islandia" },
  { code: "mh", name: "Islas Marshall" },
  { code: "sb", name: "Islas Salomón" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italia" },
  { code: "jm", name: "Jamaica" },
  { code: "jp", name: "Japón" },
  { code: "jo", name: "Jordania" },
  { code: "kz", name: "Kazajistán" },
  { code: "ke", name: "Kenia" },
  { code: "kg", name: "Kirguistán" },
  { code: "ki", name: "Kiribati" },
  { code: "kw", name: "Kuwait" },
  { code: "la", name: "Laos" },
  { code: "ls", name: "Lesoto" },
  { code: "lv", name: "Letonia" },
  { code: "lb", name: "Líbano" },
  { code: "lr", name: "Liberia" },
  { code: "ly", name: "Libia" },
  { code: "li", name: "Liechtenstein" },
  { code: "lt", name: "Lituania" },
  { code: "lu", name: "Luxemburgo" },
  { code: "mg", name: "Madagascar" },
  { code: "my", name: "Malasia" },
  { code: "mw", name: "Malaui" },
  { code: "mv", name: "Maldivas" },
  { code: "ml", name: "Malí" },
  { code: "mt", name: "Malta" },
  { code: "ma", name: "Marruecos" },
  { code: "mu", name: "Mauricio" },
  { code: "mr", name: "Mauritania" },
  { code: "mx", name: "México" },
  { code: "fm", name: "Micronesia" },
  { code: "md", name: "Moldavia" },
  { code: "mc", name: "Mónaco" },
  { code: "mn", name: "Mongolia" },
  { code: "me", name: "Montenegro" },
  { code: "mz", name: "Mozambique" },
  { code: "na", name: "Namibia" },
  { code: "nr", name: "Nauru" },
  { code: "np", name: "Nepal" },
  { code: "ni", name: "Nicaragua" },
  { code: "ne", name: "Níger" },
  { code: "ng", name: "Nigeria" },
  { code: "no", name: "Noruega" },
  { code: "nz", name: "Nueva Zelanda" },
  { code: "om", name: "Omán" },
  { code: "nl", name: "Países Bajos" },
  { code: "pk", name: "Pakistán" },
  { code: "pw", name: "Palaos" },
  { code: "pa", name: "Panamá" },
  { code: "pg", name: "Papúa Nueva Guinea" },
  { code: "py", name: "Paraguay" },
  { code: "pe", name: "Perú" },
  { code: "pl", name: "Polonia" },
  { code: "pt", name: "Portugal" },
  { code: "gb", name: "Reino Unido" },
  { code: "cf", name: "República Centroafricana" },
  { code: "cz", name: "República Checa" },
  { code: "cg", name: "República del Congo" },
  { code: "cd", name: "República Democrática del Congo" },
  { code: "do", name: "República Dominicana" },
  { code: "rw", name: "Ruanda" },
  { code: "ro", name: "Rumania" },
  { code: "ru", name: "Rusia" },
  { code: "ws", name: "Samoa" },
  { code: "kn", name: "San Cristóbal y Nieves" },
  { code: "sm", name: "San Marino" },
  { code: "vc", name: "San Vicente y las Granadinas" },
  { code: "lc", name: "Santa Lucía" },
  { code: "st", name: "Santo Tomé y Príncipe" },
  { code: "sn", name: "Senegal" },
  { code: "rs", name: "Serbia" },
  { code: "sc", name: "Seychelles" },
  { code: "sl", name: "Sierra Leona" },
  { code: "sg", name: "Singapur" },
  { code: "sy", name: "Siria" },
  { code: "so", name: "Somalia" },
  { code: "lk", name: "Sri Lanka" },
  { code: "za", name: "Sudáfrica" },
  { code: "sd", name: "Sudán" },
  { code: "ss", name: "Sudán del Sur" },
  { code: "se", name: "Suecia" },
  { code: "ch", name: "Suiza" },
  { code: "sr", name: "Surinam" },
  { code: "th", name: "Tailandia" },
  { code: "tz", name: "Tanzania" },
  { code: "tj", name: "Tayikistán" },
  { code: "tl", name: "Timor Oriental" },
  { code: "tg", name: "Togo" },
  { code: "to", name: "Tonga" },
  { code: "tt", name: "Trinidad y Tobago" },
  { code: "tn", name: "Túnez" },
  { code: "tm", name: "Turkmenistán" },
  { code: "tr", name: "Turquía" },
  { code: "tv", name: "Tuvalu" },
  { code: "ua", name: "Ucrania" },
  { code: "ug", name: "Uganda" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistán" },
  { code: "vu", name: "Vanuatu" },
  { code: "ve", name: "Venezuela" },
  { code: "vn", name: "Vietnam" },
  { code: "ye", name: "Yemen" },
  { code: "dj", name: "Yibuti" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabue" }
]

export const bookingHeaders = [
    {
        name: 'CREADO',
        value: 'createdAt',
    },
    {
        name: 'SERVICIO',
        value: 'title',
    },
    {
        name: 'NOMBRE',
        value: 'name',
    },
    {
        name: 'APELLIDO',
        value: 'lastName',
    },
    {
        name: 'EDAD',
        value: 'age',
    },
    {
        name: 'TEL.',
        value: 'phone',
    },
    {
        name: 'EMAIL',
        value: 'email',
    },
    {
        name: 'FECHA DE CITA',
        value: 'date',
    },
    {
        name: 'PRECIO',
        value: 'amountPayed',
    },
    {
        name: 'PAGADO',
        value: 'isPaid',
    },
]

export const serviceHeaders = [
    {
        name: 'CREADO',
        value: 'createdAt',
    },
    {
        name: 'TÍTULO',
        value: 'title',
    },
    {
        name: 'SUBTÍTULO',
        value: 'subtitle',
    },
    {
        name: 'DESCRIPCIÓN',
        value: 'description',
    },
    {
        name: 'PRECIO €',
        value: 'priceEUR',
    },
    {
        name: 'TIPO',
        value: 'type',
    },
    {
        name: 'DESCUENTOS',
        value: 'discounts',
    },
    {
        name: 'ACTIVO',
        value: 'active',
    },
]